/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedUiSamplesImport } from './routes/_authed/ui-samples'
import { Route as AuthedTodosImport } from './routes/_authed/todos'
import { Route as AuthedPostsImport } from './routes/_authed/posts'
import { Route as AuthedNotesImport } from './routes/_authed/notes'
import { Route as AuthedDeferredImport } from './routes/_authed/deferred'
import { Route as AuthedPostsIndexImport } from './routes/_authed/posts.index'
import { Route as AuthedProfileSplatImport } from './routes/_authed/profile.$'
import { Route as AuthedPostsNewImport } from './routes/_authed/posts.new'
import { Route as AuthedPostsPostIdImport } from './routes/_authed/posts.$postId'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedUiSamplesRoute = AuthedUiSamplesImport.update({
  id: '/ui-samples',
  path: '/ui-samples',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedTodosRoute = AuthedTodosImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsRoute = AuthedPostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedNotesRoute = AuthedNotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDeferredRoute = AuthedDeferredImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsIndexRoute = AuthedPostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)

const AuthedProfileSplatRoute = AuthedProfileSplatImport.update({
  id: '/profile/$',
  path: '/profile/$',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsNewRoute = AuthedPostsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedPostsRoute,
} as any)

const AuthedPostsPostIdRoute = AuthedPostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/deferred': {
      id: '/_authed/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof AuthedDeferredImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/todos': {
      id: '/_authed/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthedTodosImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/ui-samples': {
      id: '/_authed/ui-samples'
      path: '/ui-samples'
      fullPath: '/ui-samples'
      preLoaderRoute: typeof AuthedUiSamplesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdImport
      parentRoute: typeof AuthedPostsImport
    }
    '/_authed/posts/new': {
      id: '/_authed/posts/new'
      path: '/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthedPostsNewImport
      parentRoute: typeof AuthedPostsImport
    }
    '/_authed/profile/$': {
      id: '/_authed/profile/$'
      path: '/profile/$'
      fullPath: '/profile/$'
      preLoaderRoute: typeof AuthedProfileSplatImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexImport
      parentRoute: typeof AuthedPostsImport
    }
  }
}

// Create and export the route tree

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsNewRoute: typeof AuthedPostsNewRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsNewRoute: AuthedPostsNewRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDeferredRoute: typeof AuthedDeferredRoute
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedTodosRoute: typeof AuthedTodosRoute
  AuthedUiSamplesRoute: typeof AuthedUiSamplesRoute
  AuthedProfileSplatRoute: typeof AuthedProfileSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDeferredRoute: AuthedDeferredRoute,
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedTodosRoute: AuthedTodosRoute,
  AuthedUiSamplesRoute: AuthedUiSamplesRoute,
  AuthedProfileSplatRoute: AuthedProfileSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/deferred': typeof AuthedDeferredRoute
  '/notes': typeof AuthedNotesRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/todos': typeof AuthedTodosRoute
  '/ui-samples': typeof AuthedUiSamplesRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/posts/': typeof AuthedPostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/deferred': typeof AuthedDeferredRoute
  '/notes': typeof AuthedNotesRoute
  '/todos': typeof AuthedTodosRoute
  '/ui-samples': typeof AuthedUiSamplesRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/posts': typeof AuthedPostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/deferred': typeof AuthedDeferredRoute
  '/_authed/notes': typeof AuthedNotesRoute
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/_authed/todos': typeof AuthedTodosRoute
  '/_authed/ui-samples': typeof AuthedUiSamplesRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/posts/new': typeof AuthedPostsNewRoute
  '/_authed/profile/$': typeof AuthedProfileSplatRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/deferred'
    | '/notes'
    | '/posts'
    | '/todos'
    | '/ui-samples'
    | '/posts/$postId'
    | '/posts/new'
    | '/profile/$'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/deferred'
    | '/notes'
    | '/todos'
    | '/ui-samples'
    | '/posts/$postId'
    | '/posts/new'
    | '/profile/$'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/deferred'
    | '/_authed/notes'
    | '/_authed/posts'
    | '/_authed/todos'
    | '/_authed/ui-samples'
    | '/_authed/posts/$postId'
    | '/_authed/posts/new'
    | '/_authed/profile/$'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/deferred",
        "/_authed/notes",
        "/_authed/posts",
        "/_authed/todos",
        "/_authed/ui-samples",
        "/_authed/profile/$"
      ]
    },
    "/_authed/deferred": {
      "filePath": "_authed/deferred.tsx",
      "parent": "/_authed"
    },
    "/_authed/notes": {
      "filePath": "_authed/notes.tsx",
      "parent": "/_authed"
    },
    "/_authed/posts": {
      "filePath": "_authed/posts.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/posts/$postId",
        "/_authed/posts/new",
        "/_authed/posts/"
      ]
    },
    "/_authed/todos": {
      "filePath": "_authed/todos.tsx",
      "parent": "/_authed"
    },
    "/_authed/ui-samples": {
      "filePath": "_authed/ui-samples.tsx",
      "parent": "/_authed"
    },
    "/_authed/posts/$postId": {
      "filePath": "_authed/posts.$postId.tsx",
      "parent": "/_authed/posts"
    },
    "/_authed/posts/new": {
      "filePath": "_authed/posts.new.tsx",
      "parent": "/_authed/posts"
    },
    "/_authed/profile/$": {
      "filePath": "_authed/profile.$.tsx",
      "parent": "/_authed"
    },
    "/_authed/posts/": {
      "filePath": "_authed/posts.index.tsx",
      "parent": "/_authed/posts"
    }
  }
}
ROUTE_MANIFEST_END */
